### ISSUE TITLE
Plugin fails with Yarn 4.0.1

### ISSUE THREAD

**Issue by danielrentz** [kristian/yarn-plugin-optional-resolution#1]
Hi there!

We used this plugin successfully with Yarn 3.6.3. However, after upgrading to Yarn 4.0.1, the plugin fails with a type error.

```
SyntaxError: [my-internal-package]@npm:0.0.1: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at .../.yarn/plugins/@yarnpkg/plugin-optional-resolution.cjs:10:16
```

Problem seems to be in the line https://github.com/kristian/yarn-plugin-optional-resolution/blob/main/sources/installHooks.ts#L92. In Yarn 4.0.1, the `result.body` is already the parsed object (changing assignment to `const body = result.body` will cause successful installation).

**Comment by kristian** [comment]
Thanks @danielrentz I will look into it later on.

**Comment by kristian** [comment]
Fixed, hope this helps! :)

**Comment by danielrentz** [comment]
@kristian  Thank you very much for the fix (and for the plugin as well of course) :) 

Trying to install https://raw.githubusercontent.com/kristian/yarn-plugin-optional-resolution/v1.2.0/bundles/%40yarnpkg/plugin-optional-resolution.js results in 404 currently. Is there some publish step needed, or just some patience?

**Comment by kristian** [comment]
Ah sorry, I forgot to push a tag, I will do so, as soon as I get back home, sorry

**Comment by kristian** [comment]
@danielrentz Should work now, Sorry for the inconvenience!

**Comment by danielrentz** [comment]
Perfect, thank you very much!
